CREATE TABLE agencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL
);


CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    logo text NOT NULL,
    group_photo text NOT NULL,
    ticker text NOT NULL,
    gender text DEFAULT 'boy',
    type text DEFAULT 'group',
    agency_id bigint,
    acronyms text DEFAULT '',
    FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL
);


CREATE TABLE artist_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    profile_image text,
    team_id bigint,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL
);