name: Build and Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-unknown-linux-gnu

      - name: Install dependencies
        run: sudo apt update; sudo apt upgrade; sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross libssl-dev

      - name: Configure cargo for aarch64
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml

      - name: Build
        run: |
          cargo build --release --target=aarch64-unknown-linux-gnu

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/aarch64-unknown-linux-gnu/release/kup-of-tea-be"
          target: "/home/ubuntu/kup"
          strip_components: 3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart kup.service
